### ISSUE TITLE
iOS 10 no longer supported with version 0.3.9.6

### ISSUE THREAD

**Issue by EIDD8680** [google/nanopb-podspec#15]
Same report than https://github.com/nanopb/nanopb/issues/586.

### Steps to reproduce the issue
1. Install firebase version 6.31.1 with cocoapods, include nanopb version 0.3.9.6 (pod spec 1.30906.0).
2. In Xcode, archived with iOS Deployment Target iOS 10.0.

### What happens?

**Ignoring file** /Users/xxxxxx/Library/Developer/Xcode/DerivedData/xxxxxx-xxxxx/Build/Intermediates.noindex/ArchiveIntermediates/xxxxxxx/BuildProductsPath/Recette-iphoneos/nanopb/libnanopb.a, building for iOS-armv7 but attempting to link with file built for iOS-arm64
Undefined symbol: _pb_encode_varint
Undefined symbol: _pb_decode_varint
Undefined symbol: _pb_encode_string
Undefined symbol: _pb_encode_submessage
Undefined symbol: _pb_encode_tag_for_field
Undefined symbol: _pb_read
Undefined symbol: _pb_istream_from_buffer
Undefined symbol: _pb_ostream_from_buffer
Undefined symbol: _pb_decode
Undefined symbol: _pb_release
Undefined symbol: _pb_encode

### What should happen?
nothing (no warning, no ignoring file, no error). Works well with nonapb version 0.3.9.1 (pod spec 0.3.901).

**Comment by paulb777** [comment]
Hmm, there shouldn't be anything different between the structure of those two versions.

This might be the result of a corrupt build state. Please try removing DerivedData and restarting.

If you're still seeing the issue, let us know the Xcode and CocoaPods versions

**Comment by EIDD8680** [comment]
DerivedData deleted and podfile.lock deleted (and pod folder deleted and pod deintegrate). Same issue. 

- Xcode 11.3.1
- CocoaPods 1.9.3

**Comment by paulb777** [comment]
I'm not able to reproduce and there are likely many Firebase users doing this without issue.  Perhaps, there is something strange about platform settings in the Xcode Build Settings?

We'll likely need a reproducible example to provide additional help.

**Comment by EIDD8680** [comment]
Hello,
With a new empty project with just firebase 6.31.1 in Podfile, I reproduce the issue.

[TestNanopb.zip](https://github.com/google/nanopb-podspec/files/5266214/TestNanopb.zip)

**Comment by paulb777** [comment]
The issue seems to be something specific to your configuration and `git@sd-gitlab.cm-cic.fr:mobile-ios/Specs.git`.

I can reproduce with the xcworkspace you sent and I don't see the pods being compiled for arm7.  However, if I remove the private source from the Podfile and `pod install`. The arm7 builds happen and the app successfull archives:

![Screen Shot 2020-09-23 at 9 14 59 AM](https://user-images.githubusercontent.com/73870/94040263-932a8c80-fd7d-11ea-8129-6e2d0232ff1f.png)

**Comment by EIDD8680** [comment]
OK, I will analyze this. Thank you for your help.
