### ISSUE TITLE
License Not clearly specified

### ISSUE THREAD

**Issue by syedhaiderdev** [google/nanopb-podspec#20]
The license type is not properly specified for "nanopb"
1. This repo has a license type of MIT License: https://github.com/google/nanopb-podspec/blob/master/LICENSE
2. Whereas the official repo of nanopb: https://github.com/nanopb/nanopb/blob/master/LICENSE.txt shows license as zlib License.

**Comment by paulb777** [comment]
Thanks for the report. The license in this repo was only specifying the license for the podspec. I added the library reference in #21.
