### ISSUE TITLE
Download server is unavailable

### ISSUE THREAD

**Issue by kevinrenskers** [google/nanopb-podspec#3]
http://koti.kapsi.fi/~jpa/nanopb/download/nanopb-0.3.8.tar.gz is not available (gives a 503) but https://github.com/nanopb/nanopb/archive/0.3.8.tar.gz is. Can you maybe use that github link instead?

**Comment by buddha-sofi** [comment]
I'm having the same issue as well.

**Comment by davidair** [comment]
The podspec has been updated and pushed to CocoaPods.
